services:
  mediasoup-app:
    build: .
    image: vibecast-server
    volumes:
      - ./src:/server/src
      - ./prisma:/server/prisma
      - ./.env:/server/.env
    ports:
      - "5001:5001"
      - "4000:4000"
      - "40000-40050:40000-40050/udp"
