global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["18.209.221.141:9100"]

  - job_name: "mediasoup-app"
    static_configs:
      - targets: ["18.209.221.141:5001"]

  - job_name: "pushgateway"
    static_configs:
      - targets: ["18.209.221.141:9091"]
