global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "node-exporter"

    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "mediasoup-app"
    static_configs:
      - targets: ["mediasoup-app:5001"]

  - job_name: "pushgateway"
    static_configs:
      - targets: ["pushgateway:9091"]
